/**
 * Stubbed codec types for pallet events.
 *
 * In a Subsquid project these are generated by `sqd typegen` from the
 * runtime metadata. Until pallet-suite emits a stable metadata artifact,
 * we ship hand-typed shapes that mirror the on-chain event signatures
 * declared in each pallet's `#[pallet::event]` block.
 *
 * When the runtime is wired and `sqd typegen` runs, replace this file
 * with the auto-generated output. All call sites import from this module
 * by name, so the migration is a 1-line `src/handlers/*.ts` change.
 */

// --- pallet-job-market --------------------------------------------------------
export interface JobSubmittedEvent {
    jobId: string; // 32-byte hex
    customer: string; // ss58
    modelId: string;
    adapterId: string | null;
    submittedAt: number;
}

export interface JobAssignedEvent {
    jobId: string;
    operator: string;
}

export interface JobFinalizedEvent {
    jobId: string;
    receiptRoot: string;
    costMicroUSD: bigint;
    finalizedAt: number;
}

export interface JobDisputedEvent {
    jobId: string;
    disputant: string;
    evidenceCid: string;
}

// --- pallet-bme ---------------------------------------------------------------
export interface BurnedEvent {
    customer: string;
    jobId: string | null;
    amount: bigint;
    twapPriceMicroUSD: bigint;
}

export interface MintedEvent {
    operator: string;
    jobId: string | null;
    amount: bigint;
    epoch: number;
}

// --- pallet-slashing ----------------------------------------------------------
export interface SlashOpenedEvent {
    operator: string;
    amount: bigint;
    kind: 'MissedHeartbeat' | 'DisputeUpheld' | 'AttestationRevoked' | 'ReceiptMismatch' | 'Other';
    reasonHash: string;
}

export interface SlashConfirmedEvent {
    operator: string;
    amount: bigint;
    resolvedAt: number;
}

export interface DisputeOpenedEvent {
    operator: string;
    disputant: string;
    evidenceCid: string;
}

// --- pallet-operator-stake ----------------------------------------------------
export interface RegisteredEvent {
    operator: string;
    stake: bigint;
    attestationCid: string | null;
}

export interface HeartbeatEvent {
    operator: string;
    height: number;
}

export interface OperatorSlashedEvent {
    operator: string;
    amount: bigint;
}

/**
 * Permissive decoder used by handlers: takes the raw `event.args` field
 * (whose shape depends on the on-chain encoding) and casts it to the
 * declared interface. Once `sqd typegen` runs, this gets replaced by
 * versioned decoders that round-trip through SCALE.
 */
export function decode<T>(args: unknown): T {
    return args as T;
}
